# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hello Our World
tagline:             'Historical & Philosophical Ramblings of a Computer Science Engineer'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://yuxiaotan.github.io
baseurl:             /
paginate:            1

# About/contact
author:
  name:              Yuxiao Tan
  url:               https://github.com/yuxiaotan
  email:             yt358@cornell.edu

# Custom vars
version:             1.0.0
